spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tiny_task
    username: tiny_task
    password: demo123

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: validate
      
  mail:
    host: smtp.gmail.com
    port: 587
    username: my.mail@gmail.com
    password: my.password
    protocol: smtp
    tls: true
    properties.mail.smtp:
        auth: true
        starttls.enable: true
        ssl.trust: smtp.gmail.com
    debug: true

logging:
  level:
    com.coyoapp.tinytask: DEBUG
